### ISSUE TITLE
`cornify_add()` in Day 12 doesn't work

### ISSUE THREAD

**Issue by jesseca-ac** [wesbos/Wes-Bos-Video-Notes#37]
`cornify_add()` in Day 12 doesn't work and only shows the count of cornifies on screen.

Only runs this...
`cornify_count += 1;`

this...
`    if(cornify_count == 1) {
        p.innerHTML = 'You cornified!';
    } else {
        p.innerHTML = 'You cornified '+cornify_count+' times!';
    }`

**Comment by wesbos** [comment]
Looks like the remote unicorn resource was down. I patched the package with a local version of the cornify.js:

https://github.com/wesbos/JavaScript30/commit/25cc79381b1a7d190c4318712c78140ccfb1f750

Just download cornify.js and replace the script tag in your html file, or just re-download the starter files for day 12
