### ISSUE TITLE
TypeError: plugin is not a function

### ISSUE THREAD

**Issue by therealrodk** [wesbos/Wes-Bos-Video-Notes#38]
This is my first time working with React, and I am getting the following error while trying to follow along with Lesson #5: Loading CSS into our React Application.

I got this error immediately after adding `import "./css/style.css";` to `index.js`.

![Screen Shot 2023-05-17 at 08 52 36](https://github.com/wesbos/Wes-Bos-Video-Notes/assets/28791642/c782d719-0ffa-45ae-aa36-be8366bcba1f)

**Comment by wesbos** [comment]
Hey! Join the slack chat and we will help you out! These notes aren't the spot to get help
